<style>
    #paytr_taksit_tablosu{clear: both;font-size: 12px;max-width: 1200px;text-align: center;font-family: Arial, sans-serif;}
    #paytr_taksit_tablosu::before {display: table;content: " ";}
    #paytr_taksit_tablosu::after {content: "";clear: both;display: table;}
    .taksit-tablosu-wrapper{margin: 5px;width: 280px;padding: 12px;cursor: default;text-align: center;display: inline-block;border: 1px solid #e1e1e1;}
    .taksit-logo img{max-height: 28px;padding-bottom: 10px;}
    .taksit-tutari-text{float: left;width: 126px;color: #a2a2a2;margin-bottom: 5px;}
    .taksit-tutar-wrapper{display: inline-block;background-color: #f7f7f7;}
    .taksit-tutar-wrapper:hover{background-color: #e8e8e8;}
    .taksit-tutari{float: left;width: 126px;padding: 6px 0;color: #474747;border: 2px solid #ffffff;}
    .taksit-tutari-bold{font-weight: bold;}
    @media all and (max-width: 600px) {.taksit-tablosu-wrapper {margin: 5px 0;}}
</style>
<input type="hidden" id="paytr_installment_table_amount"/>
<div id="paytr_taksit_tablosu"></div>
<script type="text/javascript">
    requirejs(['jquery'], function(jQuery){
        jQuery('#paytr_installment_table_amount').on('change', function() {
            jQuery( "#paytr_installment_table_script" ).remove();
            let s = document.createElement("script");
            s.type = "text/javascript";
            s.id = "paytr_installment_table_script";
            const token = "<?= $block->escapeJs($block->getInstallmentTableToken()) ?>";
            const merchantId = "<?= $block->escapeJs($block->getMerchantId()) ?>";
            const maxInstallment = "<?= $block->escapeJs($block->installmentSettings()['max_installment']) ?>";
            const showAll = "<?= $block->escapeJs($block->getInstallmentTableShowAll()) ?>";

            s.src = "https://www.paytr.com/odeme/taksit-tablosu/v2"
                + "?token=" + token
                + "&merchant_id=" + merchantId
                + "&amount=" + jQuery(this).val()
                + "&taksit=" + maxInstallment
                + "&tumu=" + showAll;
            jQuery("body").append(s);
        });
    });
</script>
