<iframe src="https://www.paytr.com/odeme/guvenli/<?php echo json_decode($this->getAction())->token;?>" id="paytriframe" frameborder="0" scrolling="no" style="width: 100%;"></iframe>
<script type="text/javascript">
    require([
        "Paytr_Payment/js/iframeResizer.min",
        "domReady"
    ], function (iFrameResize) {
        iFrameResize({},'#paytriframe');
    });
</script>
<script type="text/javascript">
    setTimeout(function(){
        alert("Bu işlem için ayrılan süre dolmuştur. Lütfen işlemi tekrar başlatın.");
        window.location.replace("<?php echo json_decode($this->getAction())->redirect_url;?>");
    }, <?php echo json_decode($this->getAction())->timeout * 60 * 1000;?>);
</script>
